package com.ferreteria.ferreteria;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1



/**
 * DevolucionId generated by hbm2java
 */
public class DevolucionId  implements java.io.Serializable {


     private long idFactura;
     private long idProducto;

    public DevolucionId() {
    }

    public DevolucionId(long idFactura, long idProducto) {
       this.idFactura = idFactura;
       this.idProducto = idProducto;
    }
   
    public long getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(long idFactura) {
        this.idFactura = idFactura;
    }
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DevolucionId) ) return false;
		 DevolucionId castOther = ( DevolucionId ) other; 
         
		 return (this.getIdFactura()==castOther.getIdFactura())
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdFactura();
         result = 37 * result + (int) this.getIdProducto();
         return result;
   }   


}


