package com.ferreteria.ferreteria;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Id;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {

    @Id
    @Column
     private long nitProveedor;
    @Column
     private String nombreProveedor;
    @Column
     private String emailProveedor;
    @Column
     private Long telefonoProveedor;
    @Column
     private Set facturas = new HashSet(0);
     private Set precios = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(long nitProveedor) {
        this.nitProveedor = nitProveedor;
    }
    public Proveedor(long nitProveedor, String nombreProveedor, String emailProveedor, Long telefonoProveedor, Set facturas, Set precios) {
       this.nitProveedor = nitProveedor;
       this.nombreProveedor = nombreProveedor;
       this.emailProveedor = emailProveedor;
       this.telefonoProveedor = telefonoProveedor;
       this.facturas = facturas;
       this.precios = precios;
    }
   
    public long getNitProveedor() {
        return this.nitProveedor;
    }
    
    public void setNitProveedor(long nitProveedor) {
        this.nitProveedor = nitProveedor;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public String getEmailProveedor() {
        return this.emailProveedor;
    }
    
    public void setEmailProveedor(String emailProveedor) {
        this.emailProveedor = emailProveedor;
    }
    public Long getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(Long telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Set precios) {
        this.precios = precios;
    }




}


