package model.pojos;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1



/**
 * Colaborador generated by hbm2java
 */
public class Colaborador  implements java.io.Serializable {


     private long idUsuario;
     private Ferreteria ferreteria;
     private String nombreUsuario;
     private String contrasena;
     private Short estado;

    public Colaborador() {
    }

	
    public Colaborador(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Colaborador(long idUsuario, Ferreteria ferreteria, String nombreUsuario, String contrasena, Short estado) {
       this.idUsuario = idUsuario;
       this.ferreteria = ferreteria;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.estado = estado;
    }
   
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Ferreteria getFerreteria() {
        return this.ferreteria;
    }
    
    public void setFerreteria(Ferreteria ferreteria) {
        this.ferreteria = ferreteria;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Short getEstado() {
        return this.estado;
    }
    
    public void setEstado(Short estado) {
        this.estado = estado;
    }




}


