package model.pojos;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1



/**
 * Devolucion generated by hbm2java
 */
public class Devolucion  implements java.io.Serializable {


     private DevolucionId id;
     private Factura factura;
     private Producto producto;
     private Integer cantidad;
     private Double precioUnidad;
     private Float iva;

    public Devolucion() {
    }

	
    public Devolucion(DevolucionId id, Factura factura, Producto producto) {
        this.id = id;
        this.factura = factura;
        this.producto = producto;
    }
    public Devolucion(DevolucionId id, Factura factura, Producto producto, Integer cantidad, Double precioUnidad, Float iva) {
       this.id = id;
       this.factura = factura;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioUnidad = precioUnidad;
       this.iva = iva;
    }
   
    public DevolucionId getId() {
        return this.id;
    }
    
    public void setId(DevolucionId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(Double precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }




}


