package model.pojos;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ferreteria generated by hbm2java
 */
public class Ferreteria  implements java.io.Serializable {


     private String nombre;
     private Set productos = new HashSet(0);
     private Set colaboradors = new HashSet(0);
     private Set admins = new HashSet(0);

    public Ferreteria() {
    }

	
    public Ferreteria(String nombre) {
        this.nombre = nombre;
    }
    public Ferreteria(String nombre, Set productos, Set colaboradors, Set admins) {
       this.nombre = nombre;
       this.productos = productos;
       this.colaboradors = colaboradors;
       this.admins = admins;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    public Set getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set colaboradors) {
        this.colaboradors = colaboradors;
    }
    public Set getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set admins) {
        this.admins = admins;
    }




}


