package model.pojos;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1



/**
 * PrecioId generated by hbm2java
 */
public class PrecioId  implements java.io.Serializable {


     private long nitProveedor;
     private long idProducto;

    public PrecioId() {
    }

    public PrecioId(long nitProveedor, long idProducto) {
       this.nitProveedor = nitProveedor;
       this.idProducto = idProducto;
    }
   
    public long getNitProveedor() {
        return this.nitProveedor;
    }
    
    public void setNitProveedor(long nitProveedor) {
        this.nitProveedor = nitProveedor;
    }
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrecioId) ) return false;
		 PrecioId castOther = ( PrecioId ) other; 
         
		 return (this.getNitProveedor()==castOther.getNitProveedor())
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNitProveedor();
         result = 37 * result + (int) this.getIdProducto();
         return result;
   }   


}


