package model.pojos;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private long idProducto;
     private Ferreteria ferreteria;
     private String nombreProducto;
     private Float porcentajeGanacia;
     private Float iva;
     private Set precios = new HashSet(0);
     private Set prouctoFacturas = new HashSet(0);
     private Set devolucions = new HashSet(0);

    public Producto() {
    }

	
    public Producto(long idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(long idProducto, Ferreteria ferreteria, String nombreProducto, Float porcentajeGanacia, Float iva, Set precios, Set prouctoFacturas, Set devolucions) {
       this.idProducto = idProducto;
       this.ferreteria = ferreteria;
       this.nombreProducto = nombreProducto;
       this.porcentajeGanacia = porcentajeGanacia;
       this.iva = iva;
       this.precios = precios;
       this.prouctoFacturas = prouctoFacturas;
       this.devolucions = devolucions;
    }
   
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }
    public Ferreteria getFerreteria() {
        return this.ferreteria;
    }
    
    public void setFerreteria(Ferreteria ferreteria) {
        this.ferreteria = ferreteria;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Float getPorcentajeGanacia() {
        return this.porcentajeGanacia;
    }
    
    public void setPorcentajeGanacia(Float porcentajeGanacia) {
        this.porcentajeGanacia = porcentajeGanacia;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }
    public Set getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Set precios) {
        this.precios = precios;
    }
    public Set getProuctoFacturas() {
        return this.prouctoFacturas;
    }
    
    public void setProuctoFacturas(Set prouctoFacturas) {
        this.prouctoFacturas = prouctoFacturas;
    }
    public Set getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set devolucions) {
        this.devolucions = devolucions;
    }




}


