package com.ferreteria.ferreteria;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Id;




/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {

    @Id
    @Column
     private long idUsuario;
    @Column
     private Ferreteria ferreteria;
    @Column
     private String nombreUsuario;
    @Column
     private String contrasena;
    @Column
     private Short estado;

    public Admin() {
    }

	
    public Admin(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Admin(long idUsuario, Ferreteria ferreteria, String nombreUsuario, String contrasena, Short estado) {
       this.idUsuario = idUsuario;
       this.ferreteria = ferreteria;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.estado = estado;
    }
   
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Ferreteria getFerreteria() {
        return this.ferreteria;
    }
    
    public void setFerreteria(Ferreteria ferreteria) {
        this.ferreteria = ferreteria;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Short getEstado() {
        return this.estado;
    }
    
    public void setEstado(Short estado) {
        this.estado = estado;
    }




}


