package com.ferreteria.ferreteria;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Id;

/**
 * Precio generated by hbm2java
 */
public class Precio  implements java.io.Serializable {

    @Id
    @Column
     private PrecioId id;
    @Column
     private Producto producto;
    @Column
     private Proveedor proveedor;
    @Column
     private Date fechaActualizacion;
    @Column
     private Long precio;

    public Precio() {
    }

	
    public Precio(PrecioId id, Producto producto, Proveedor proveedor, Date fechaActualizacion) {
        this.id = id;
        this.producto = producto;
        this.proveedor = proveedor;
        this.fechaActualizacion = fechaActualizacion;
    }
    public Precio(PrecioId id, Producto producto, Proveedor proveedor, Date fechaActualizacion, Long precio) {
       this.id = id;
       this.producto = producto;
       this.proveedor = proveedor;
       this.fechaActualizacion = fechaActualizacion;
       this.precio = precio;
    }
   
    public PrecioId getId() {
        return this.id;
    }
    
    public void setId(PrecioId id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Long precio) {
        this.precio = precio;
    }




}


