package com.ferreteria.ferreteria;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1



/**
 * ProuctoFacturaId generated by hbm2java
 */
public class ProuctoFacturaId  implements java.io.Serializable {


     private long idProducto;
     private long idFactura;

    public ProuctoFacturaId() {
    }

    public ProuctoFacturaId(long idProducto, long idFactura) {
       this.idProducto = idProducto;
       this.idFactura = idFactura;
    }
   
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }
    public long getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(long idFactura) {
        this.idFactura = idFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProuctoFacturaId) ) return false;
		 ProuctoFacturaId castOther = ( ProuctoFacturaId ) other; 
         
		 return (this.getIdProducto()==castOther.getIdProducto())
 && (this.getIdFactura()==castOther.getIdFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdProducto();
         result = 37 * result + (int) this.getIdFactura();
         return result;
   }   


}


