package com.ferreteria.ferreteria;
// Generated 8/07/2019 12:36:17 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Id;




/**
 * ProuctoFactura generated by hbm2java
 */
public class ProuctoFactura  implements java.io.Serializable {

    @Id
    @Column
     private ProuctoFacturaId id;
    @Column
     private Factura factura;
    @Column
     private Producto producto;
    @Column
     private Integer cantidad;
    @Column
     private Double precioUnidad;
    @Column
     private Float iva;

    public ProuctoFactura() {
    }

	
    public ProuctoFactura(ProuctoFacturaId id, Factura factura, Producto producto) {
        this.id = id;
        this.factura = factura;
        this.producto = producto;
    }
    public ProuctoFactura(ProuctoFacturaId id, Factura factura, Producto producto, Integer cantidad, Double precioUnidad, Float iva) {
       this.id = id;
       this.factura = factura;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioUnidad = precioUnidad;
       this.iva = iva;
    }
   
    public ProuctoFacturaId getId() {
        return this.id;
    }
    
    public void setId(ProuctoFacturaId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(Double precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }




}


